[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3", "@aws-sdk/s3-request-presigner", "@aws-sdk/client-textract", "@supabase/supabase-js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
